<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://ctop.exchange.continent.cusdep.customs.gov.cn/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
                  name="exchangeService"
                  targetNamespace="http://ctop.exchange.continent.cusdep.customs.gov.cn/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   xmlns:tns="http://ctop.exchange.continent.cusdep.customs.gov.cn/" elementFormDefault="unqualified"
                   targetNamespace="http://ctop.exchange.continent.cusdep.customs.gov.cn/" version="1.0">

            <xs:element name="getExchangeData" type="tns:getExchangeData"/>

            <xs:element name="getExchangeDataResponse" type="tns:getExchangeDataResponse"/>

            <xs:complexType name="getExchangeData">
                <xs:sequence>
                    <xs:element minOccurs="0" name="exchangeData" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="getExchangeDataResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

        </xs:schema>
    </wsdl:types>
    <wsdl:message name="getExchangeData">
        <wsdl:part element="tns:getExchangeData" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getExchangeDataResponse">
        <wsdl:part element="tns:getExchangeDataResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ExchangeService">
        <wsdl:operation name="getExchangeData">
            <wsdl:input message="tns:getExchangeData" name="getExchangeData">
            </wsdl:input>
            <wsdl:output message="tns:getExchangeDataResponse" name="getExchangeDataResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="exchangeServiceSoapBinding" type="tns:ExchangeService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getExchangeData">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="getExchangeData">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getExchangeDataResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="exchangeService">
        <wsdl:port binding="tns:exchangeServiceSoapBinding" name="CtopKzDataAcceptServiceImplPort">
            <soap:address location="http://10.1.0.165/soap/exchangeService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>